default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight / App Store Connect"
  lane :deploy do
    sh("flutter", "build", "ipa", "--release", "--export-options-plist=ios/Runner/ExportOptions.plist")

    build_path = Dir.glob("../build/ios/ipa/*.ipa").first
    upload_to_testflight(
      ipa: build_path,
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Build IPA only (no upload)"
  lane :build do
    sh("flutter", "build", "ipa", "--release", "--export-options-plist=ios/Runner/ExportOptions.plist")
  end
end
